[tasks.build-wasm]
dependencies = ["install-wasm-bindgen", "install-wasm-support"]
script_runner = "@shell"
script = '''
cargo build --release --target wasm32-unknown-unknown
wasm-bindgen target/wasm32-unknown-unknown/release/ld52.wasm --out-dir web --no-modules --no-typescript
'''

[tasks.install-simple-http-server]
install_crate = "simple-http-server"

[tasks.install-wasm-bindgen]
install_crate = "wasm-bindgen-cli"

[tasks.install-wasm-support]
script_runner = "@shell"
script = '''
rustup target add wasm32-unknown-unknown
'''

[tasks.serve-wasm]
dependencies = ["build-wasm", "install-simple-http-server"]
script_runner = "@shell"
script = '''
hash -r
simple-http-server web --open --nocache --index
'''
